"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var jsx_runtime_1 = require("react/jsx-runtime");
var card_1 = require("./ui/card");
var input_1 = require("./ui/input");
var button_1 = require("./ui/button");
var lucide_react_1 = require("lucide-react");
var KeyMapping = function (_a) {
    var mappings = _a.mappings, updateMapping = _a.updateMapping, valueBuilders = _a.valueBuilders, openValueBuilder = _a.openValueBuilder, clearValueBuilder = _a.clearValueBuilder;
    return ((0, jsx_runtime_1.jsx)(card_1.Card, { className: "mb-6 bg-[var(--figma-color-bg-secondary)] border-[var(--figma-color-border)]", children: (0, jsx_runtime_1.jsxs)(card_1.CardContent, { className: "p-3 space-y-3", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between", children: [(0, jsx_runtime_1.jsx)("div", { className: "text-[var(--figma-color-text)] text-xs font-semibold uppercase tracking-wide", children: "Data mapping" }), (0, jsx_runtime_1.jsx)(lucide_react_1.ChevronDown, { className: "h-5 w-5 text-[var(--figma-color-text-secondary)] rotate-180" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-0", children: [(0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-[140px_1fr] gap-4 border-b-2 border-[var(--figma-color-border)] pb-1.5", children: [(0, jsx_runtime_1.jsx)("div", { className: "text-xs font-semibold text-[var(--figma-color-text)] tracking-wide px-2", children: "Key" }), (0, jsx_runtime_1.jsx)("div", { className: "text-xs font-semibold text-[var(--figma-color-text)] tracking-wide px-2", children: "Layer name" })] }), mappings.map(function (mapping) { return ((0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-[140px_1fr] gap-4 py-3 border-b border-[var(--figma-color-border)] items-center", children: [(0, jsx_runtime_1.jsx)("div", { className: "text-xs text-[var(--figma-color-text)] px-2 overflow-hidden text-ellipsis whitespace-nowrap", children: mapping.jsonKey }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2 px-2", children: [(0, jsx_runtime_1.jsx)(input_1.Input, { value: mapping.layerName, onChange: function (e) { return updateMapping(mapping.jsonKey, e.target.value); }, placeholder: "adult", className: "h-8 text-xs bg-[var(--figma-color-bg)] border-[var(--figma-color-border)] text-[var(--figma-color-text)]" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex gap-1 min-w-12", children: [(0, jsx_runtime_1.jsx)(button_1.Button, { variant: "ghost", size: "icon", className: "h-5 w-5 p-0 text-[var(--figma-color-text-secondary)] hover:text-[var(--figma-color-text)] transition-colors", onClick: function () { return openValueBuilder(mapping.jsonKey); }, title: "Build custom value", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Edit, { className: "h-3 w-3 " }) }), valueBuilders[mapping.jsonKey] && ((0, jsx_runtime_1.jsx)(button_1.Button, { variant: "ghost", size: "icon", className: "h-5 w-5 p-0 text-[var(--figma-color-text-secondary)] hover:text-[var(--figma-color-text)] transition-colors", onClick: function () { return clearValueBuilder(mapping.jsonKey); }, title: "Clear value builder", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Trash2, { className: "h-3 w-3" }) }))] })] })] }, mapping.jsonKey)); })] })] }) }));
};
exports.default = KeyMapping;
